#!/bin/bash

AWS_PROFILE=ion-nonprod
AWS_REGION=us-east-1

instanceId=$(aws ec2 describe-instances \
     --profile "$AWS_PROFILE" \
     --region "$AWS_REGION" \
     --filters "Name=tag:aws:autoscaling:groupName,Values=bastion*-qa" \
     --query "Reservations[*].Instances[?State.Name == 'running'].InstanceId" \
     --output text)

host=ion-qa-0.c8l4aeuu4mil.us-east-1.rds.amazonaws.com
servicePort=5432
localPort=5431

echo
echo "An AWS SSM instance with ID $instanceId was found"

echo --target $instanceId \
     --document-name AWS-StartPortForwardingSessionToRemoteHost \
     --parameters host="${host}",portNumber="${servicePort}",localPortNumber="${localPort}"

aws ssm start-session \
     --profile "$AWS_PROFILE" \
     --region "$AWS_REGION" \
     --target $instanceId \
     --document-name AWS-StartPortForwardingSessionToRemoteHost \
     --parameters host="${host}",portNumber="${servicePort}",localPortNumber="${localPort}"

