#!/bin/bash

PROFILE="ion-prod"
REGION="us-east-1"

instanceId=$(aws ec2 describe-instances \
     --profile "$PROFILE" \
     --region "$REGION" \
     --filters "Name=tag:aws:autoscaling:groupName,Values=bastion-bastion-production" \
     --query "Reservations[*].Instances[?State.Name == 'running'].InstanceId" \
     --output text)

host=ion-production.cluster-cil42qu4w0pt.us-east-1.rds.amazonaws.com
servicePort=5432
localPort=5431

echo
echo "An AWS SSM instance with ID $instanceId was found"

echo --target $instanceId \
     --document-name AWS-StartPortForwardingSessionToRemoteHost \
     --parameters host="${host}",portNumber="${servicePort}",localPortNumber="${localPort}"

aws ssm start-session \
     --profile "$PROFILE" \
     --region "$REGION" \
     --target "$instanceId" \
     --document-name AWS-StartPortForwardingSessionToRemoteHost \
     --parameters host="${host}",portNumber="${servicePort}",localPortNumber="${localPort}"
